config/routes.rb
RoofEstimates::Application.routes.draw do
  resources :users
  resources :sessions, only: [ :new, :create, :destory ]

  root to: 'static_pages#home'

  match '/signup',    to: 'users#new'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  match '/services',  to: 'static_pages#services'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  # line up equals line below
  # before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def services
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  end
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to eXact Roof Estimates!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in to access this page." unless signed_in?
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "eXact Roof Estimates"
		if page_title.empty?
			base_title
		else
			"#{base_title} || #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	eXact Roof Estimates
  </small>
  <nav>
  	<ul>
  		<li><%= link_to "About", about_path %></li>
  		<li><%= link_to "Contact Us", contact_path %></li>
  	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top">
  	<div class="navbar-inner">
  	  <div class="container">
  	  	<%= link_to "eXact Roof Estimates", root_path, id: "logo" %>
  	  	<nav>
  	  		<ul class="nav pull-right">
  	  			<li><%= link_to "Home", root_path %></li>
  	  			<li><%= link_to "About", about_path %></li>
            <li><%= link_to "Services", services_path %></li>
  	  			<% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="3" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign In", signin_path %></li>
            <% end %>
  	  		</ul>
  	  	</nav>
  	  </div>
  	</dv>
  </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="hero-unit">
	<h1>About Page</h1>
	<p>
	  This is the about page for eXact Roof Estimates. This page will have information about this website and the service offered.
	</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<div class="hero-unit">
	<h1>Contact Us</h1>
	<p>
	  This is the contact page for eXact Roof Estimates.
	  Customers will be able to use this page to correspond with us.
	</p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>eXact Roof Estimates</h1>
  <h2>
    This is the home page for eXact Roof Estimates.
    <a href="http://www.exactroofestimates.com">www.eXactRoofEstimates.Com</a>
   </h2>

   <%= link_to "Register Now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/services.html.erb
<% provide(:title, 'Services') %>
<div class="hero-unit">
	<h1>Services Offered</h1>
	<p>
	  This is the services page for eXact Roof Estimates.
	  From this page, users will be able to view the services offered.
	</p>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Information") %>
<h1>Update Your Information</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="hero-unit">
	<h1>Sign Up</h1>

	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %>
			  <%= render 'fields', f: f %>
			  <%= f.submit "Create Account", class: "btn btn-large btn-primary" %>

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="new">
	<aside class="span4">
		<section>
			<h1>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>